# Generated by Django 3.2.9 on 2021-11-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courses_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='free_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
