# Generated by Django 3.2.9 on 2021-11-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20211121_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='description',
            field=models.CharField(default='he ka kdiadkfjakjidfklajdlkfjaldkfjladkjfadfldfadfa', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courses',
            name='free_price',
            field=models.BooleanField(default=False, verbose_name='Free Course'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.DecimalField(decimal_places=2, default=234, max_digits=5),
            preserve_default=False,
        ),
    ]
