# Generated by Django 3.2.9 on 2021-11-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20211121_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='episode',
            name='length',
            field=models.IntegerField(),
        ),
    ]
